#!/usr/bin/env python3

###
# Generates build files for the project.
# This file also includes the project configuration,
# such as compiler flags and the object matching status.
#
# Usage:
#   python3 configure.py
#   ninja
#
# Append --help to see available options.
###

import argparse
import sys
from pathlib import Path
from typing import Any, Dict, List

from tools.project import (
    Object,
    ProgressCategory,
    ProjectConfig,
    calculate_progress,
    generate_build,
    is_windows,
)

# Game versions
DEFAULT_VERSION = 0
VERSIONS = [
    "GW4E69",  # 0
]

parser = argparse.ArgumentParser()
parser.add_argument(
    "mode",
    choices=["configure", "progress"],
    default="configure",
    help="script mode (default: configure)",
    nargs="?",
)
parser.add_argument(
    "-v",
    "--version",
    choices=VERSIONS,
    type=str.upper,
    default=VERSIONS[DEFAULT_VERSION],
    help="version to build",
)
parser.add_argument(
    "--build-dir",
    metavar="DIR",
    type=Path,
    default=Path("build"),
    help="base build directory (default: build)",
)
parser.add_argument(
    "--binutils",
    metavar="BINARY",
    type=Path,
    help="path to binutils (optional)",
)
parser.add_argument(
    "--compilers",
    metavar="DIR",
    type=Path,
    help="path to compilers (optional)",
)
parser.add_argument(
    "--map",
    action="store_true",
    help="generate map file(s)",
)
parser.add_argument(
    "--debug",
    action="store_true",
    help="build with debug info (non-matching)",
)
if not is_windows():
    parser.add_argument(
        "--wrapper",
        metavar="BINARY",
        type=Path,
        help="path to wibo or wine (optional)",
    )
parser.add_argument(
    "--dtk",
    metavar="BINARY | DIR",
    type=Path,
    help="path to decomp-toolkit binary or source (optional)",
)
parser.add_argument(
    "--objdiff",
    metavar="BINARY | DIR",
    type=Path,
    help="path to objdiff-cli binary or source (optional)",
)
parser.add_argument(
    "--sjiswrap",
    metavar="EXE",
    type=Path,
    help="path to sjiswrap.exe (optional)",
)
parser.add_argument(
    "--ninja",
    metavar="BINARY",
    type=Path,
    help="path to ninja binary (optional)",
)
parser.add_argument(
    "--verbose",
    action="store_true",
    help="print verbose output",
)
parser.add_argument(
    "--non-matching",
    dest="non_matching",
    action="store_true",
    help="builds equivalent (but non-matching) or modded objects",
)
parser.add_argument(
    "--warn",
    dest="warn",
    type=str,
    choices=["all", "off", "error"],
    help="how to handle warnings",
)
parser.add_argument(
    "--no-progress",
    dest="progress",
    action="store_false",
    help="disable progress calculation",
)
args = parser.parse_args()

config = ProjectConfig()
config.version = str(args.version)
version_num = VERSIONS.index(config.version)

# Apply arguments
config.build_dir = args.build_dir
config.dtk_path = args.dtk
config.objdiff_path = args.objdiff
config.binutils_path = args.binutils
config.compilers_path = args.compilers
config.generate_map = args.map
config.non_matching = args.non_matching
config.sjiswrap_path = args.sjiswrap
config.ninja_path = args.ninja
config.progress = args.progress
if not is_windows():
    config.wrapper = args.wrapper
# Don't build asm unless we're --non-matching
if not config.non_matching:
    config.asm_dir = None

# Tool versions
config.binutils_tag = "2.42-2"
config.compilers_tag = "20251118"
config.dtk_tag = "v1.8.3"
config.objdiff_tag = "v3.6.1"
config.sjiswrap_tag = "v1.2.2"
config.wibo_tag = "1.0.3"

# Project
config.config_path = Path("config") / config.version / "config.yml"
config.check_sha_path = Path("config") / config.version / "build.sha1"
config.asflags = [
    "-mgekko",
    "--strip-local-absolute",
    "-I include",
    f"-I build/{config.version}/include",
    f"--defsym BUILD_VERSION={version_num}",
]
config.ldflags = [
    "-fp hardware",
    "-nodefaults",
]
if args.debug:
    config.ldflags.append("-g")  # Or -gdwarf-2 for Wii linkers
if args.map:
    config.ldflags.append("-mapunused")
    # config.ldflags.append("-listclosure") # For Wii linkers

# Use for any additional files that should cause a re-configure when modified
config.reconfig_deps = []

# Optional numeric ID for decomp.me preset
# Can be overridden in libraries or objects
config.scratch_preset_id = None

# Base flags, common to most GC/Wii games.
# Generally leave untouched, with overrides added below.
# Confirmed against the original binary: -proc gekko, -fp hardware, -O4.
# Not yet confirmed: -O4,p vs -O4,s, -inline mode, -str, -enum. The rest are template defaults.
cflags_base = [
    "-nodefaults",
    "-proc gekko",
    "-align powerpc",
    "-enum int",
    "-fp hardware",
    "-Cpp_exceptions off",
    "-O4,p",
    "-inline smart",  # EA code shows no automatic inlining; see docs/compiler.md
    '-pragma "cats off"',
    '-pragma "warn_notinlined off"',
    "-maxerrors 1",
    "-nosyspath",
    "-RTTI off",
    "-fp_contract on",
    "-str reuse",
    "-common on",         # EA game code: uninitialised globals are COMMON (UStream.c addresses each array separately)
    "-use_lmw_stmw on",   # EA game code: prologues use stmw/lmw, not _savegpr
    "-multibyte",  # For Wii compilers, replace with `-enc SJIS`
    "-i include",
    f"-i build/{config.version}/include",
    f"-DBUILD_VERSION={version_num}",
    f"-DVERSION_{config.version}",
    "-DVERSION=0",  # SDK revision selector for extern/sdk, see include/GameVersions.h
]

# Debug flags
if args.debug:
    # Or -sym dwarf-2 for Wii compilers
    cflags_base.extend(["-sym on", "-DDEBUG=1"])
else:
    cflags_base.append("-DNDEBUG=1")

# Warning flags
if args.warn == "all":
    cflags_base.append("-W all")
elif args.warn == "off":
    cflags_base.append("-W off")
elif args.warn == "error":
    cflags_base.append("-W error")

# Metrowerks library flags
# Nintendo prebuilt the SDK with an older compiler than EA used for the game (see docs/compiler.md).
# Settings taken from the Metroid Prime project, which links the same SDK build.
# Mirrors the Prime project's cflags_base exactly. Not derived from our cflags_base on purpose:
# the SDK needs -inline auto, the EA code needs -inline smart.
cflags_sdk = [
    "-nodefaults",
    "-proc gekko",
    "-align powerpc",
    "-enum int",
    "-fp hardware",
    "-Cpp_exceptions off",
    "-O4,p",
    "-inline auto",
    '-pragma "cats off"',
    '-pragma "warn_notinlined off"',
    "-maxerrors 1",
    "-nosyspath",
    "-RTTI off",
    "-fp_contract on",
    "-str reuse",
    "-i include",
    "-i extern/sdk/include",
    "-i extern/sdk/libc",
    f"-i build/{config.version}/include",
    "-DVERSION=0",  # SDK revision selector for extern/sdk, see include/GameVersions.h
    "-DCARD_PATCH_2003=1",  # this game's CARD library is the Apr 2 2003 patch (see docs/tw2004-notes.md)
]

# MetroTRK (extern/trk, from the Pikmin 2 decompilation): its own flags, no game includes
cflags_trk = [
    "-nodefaults",
    "-proc gekko",
    "-align powerpc",
    "-enum int",
    "-fp hardware",
    "-Cpp_exceptions off",
    "-w off",
    "-O4,p",
    "-nosyspath",
    "-RTTI off",
    "-fp_contract on",
    "-str reuse",
    "-multibyte",
    "-i extern/trk/include",
    "-i extern/trk/include/stl",
    "-DVERSION_GPVE01",
    "-use_lmw_stmw on",
    "-common off",
    "-inline auto",
    "-inline deferred",
    "-sdata 0",
    "-sdata2 0",
]

cflags_runtime = [
    *cflags_sdk,
    "-use_lmw_stmw on",
    "-str reuse,pool,readonly",
    "-gccinc",
    "-common off",
    "-char signed",
    "-inline deferred,auto",
]

# REL flags
cflags_rel = [
    *cflags_base,
    "-sdata 0",
    "-sdata2 0",
]

# Compiler / linker baseline. See docs/compiler.md for the evidence.
# GC/2.5 (mwcc 2.4.7 build 105, Feb 2003) is the working baseline. GC/2.6 and GC/2.7
# produced identical output in every test; GC/2.0 differs in ~2% of functions
# (byte masking / bit packing) and is the fallback if such a function refuses to match.
config.linker_version = "GC/2.5"


# Helper function for Dolphin libraries
def DolphinLib(lib_name: str, objects: List[Object]) -> Dict[str, Any]:
    return {
        "lib": lib_name,
        "mw_version": "GC/1.2.5n",
        "cflags": cflags_base,
        "progress_category": "sdk",
        "objects": objects,
    }


# Helper function for REL script objects
def Rel(lib_name: str, objects: List[Object]) -> Dict[str, Any]:
    return {
        "lib": lib_name,
        "mw_version": "GC/1.3.2",
        "cflags": cflags_rel,
        "progress_category": "game",
        "objects": objects,
    }


Matching = True                   # Object matches and should be linked
NonMatching = False               # Object does not match and should not be linked
Equivalent = config.non_matching  # Object should be linked when configured with --non-matching


# Object is only matching for specific versions
def MatchingFor(*versions):
    return config.version in versions


config.warn_missing_config = True
config.warn_missing_source = False
# EA's shared file library was built with SN ProDG (GCC 2.95) without optimization. See
# docs/compiler.md. tools/prodg/prodgcc.py drives the compiler; tools/project.py selects it when
# mw_version starts with "ProDG/".
cflags_gcc = [
    "-O0",
    "-nostdinc",
    "-I include",
]

config.libs = [
    {
        "lib": "TRK_MINNOW_DOLPHIN",
        "mw_version": "GC/1.3.2",
        "cflags": cflags_trk,
        "progress_category": "sdk",
        "src_dir": "extern/trk",
        "objects": [
            Object(NonMatching, "MetroTRK/mainloop.c"),
            Object(NonMatching, "MetroTRK/nubevent.c"),
            Object(NonMatching, "MetroTRK/nubinit.c"),
            Object(NonMatching, "MetroTRK/msg.c"),
            Object(NonMatching, "MetroTRK/msgbuf.c"),
            Object(NonMatching, "MetroTRK/serpoll.c"),
            Object(NonMatching, "MetroTRK/usr_put.c"),
            Object(NonMatching, "MetroTRK/dispatch.c"),
            Object(NonMatching, "MetroTRK/msghndlr.c"),
            Object(NonMatching, "MetroTRK/support.c"),
            Object(NonMatching, "MetroTRK/mutex_TRK.c"),
            Object(NonMatching, "MetroTRK/notify.c"),
            Object(NonMatching, "MetroTRK/flush_cache.c"),
            Object(NonMatching, "MetroTRK/mem_TRK.c"),
            Object(NonMatching, "MetroTRK/targimpl.c"),
            Object(NonMatching, "MetroTRK/mpc_7xx_603e.c"),
            Object(NonMatching, "MetroTRK/dolphin_trk.c"),
            Object(NonMatching, "MetroTRK/main_TRK.c"),
            Object(NonMatching, "MetroTRK/dolphin_trk_glue.c"),
            Object(NonMatching, "MetroTRK/targcont.c"),
            Object(NonMatching, "MetroTRK/target_options.c"),
            Object(NonMatching, "MetroTRK/mslsupp.c"),
            Object(NonMatching, "MetroTRK/UDP_Stubs.c"),
            Object(NonMatching, "MetroTRK/ddh/main.c"),
            Object(NonMatching, "MetroTRK/CircleBuffer.c"),
            Object(NonMatching, "MetroTRK/gdev/main.c"),
            Object(NonMatching, "MetroTRK/MWTrace.c"),
        ],
    },
    {
        "lib": "vi",
        "mw_version": "GC/1.2.5n",
        "cflags": cflags_sdk,
        "progress_category": "sdk",
        "src_dir": "extern/sdk",
        "objects": [
            Object(NonMatching, "dolphin/vi.c"),
        ],
    },
    {
        "lib": "mtx",
        "mw_version": "GC/1.2.5n",
        "cflags": cflags_sdk,
        "progress_category": "sdk",
        "src_dir": "extern/sdk",
        "objects": [
            Object(NonMatching, "dolphin/mtx/mtx.c"),
            Object(NonMatching, "dolphin/mtx/mtx44.c"),
        ],
    },
    {
        "lib": "ar",
        "mw_version": "GC/1.2.5n",
        "cflags": cflags_sdk,
        "progress_category": "sdk",
        "src_dir": "extern/sdk",
        "objects": [
            Object(NonMatching, "dolphin/ar/ar.c"),
            Object(NonMatching, "dolphin/ar/arq.c"),
        ],
    },
    {
        "lib": "ai",
        "mw_version": "GC/1.2.5n",
        "cflags": cflags_sdk,
        "progress_category": "sdk",
        "src_dir": "extern/sdk",
        "objects": [
            Object(NonMatching, "dolphin/ai.c"),
        ],
    },
    {
        "lib": "EASharedFileLib",
        "mw_version": "ProDG/3.5",
        "cflags": cflags_gcc,
        "progress_category": "game",
        "objects": [
            Object(Matching, "Common/Checksum/ChecksumCRC32.c"),
            Object(Matching, "Common/Cipher/CipherXOR.c"),
            Object(Matching, "Common/SharedFileIO/SharedFileIO.c"),
            Object(Matching, "Common/TagFile/TagFile.c"),
        ],
    },
    {
        "lib": "si",
        "mw_version": "GC/1.2.5n",
        "cflags": cflags_sdk,
        "progress_category": "sdk",
        "src_dir": "extern/sdk",
        "objects": [
            Object(NonMatching, "dolphin/si/SIBios.c"),
            Object(Matching, "dolphin/si/SISamplingRate.c"),
        ],
    },
    {
        "lib": "dsp",
        "mw_version": "GC/1.2.5n",
        "cflags": cflags_sdk,
        "progress_category": "sdk",
        "src_dir": "extern/sdk",
        "objects": [
            Object(NonMatching, "dolphin/dsp/dsp.c"),
            Object(Matching, "dolphin/dsp/dsp_task.c"),
            Object(Matching, "dolphin/dsp/dsp_debug.c"),
        ],
    },
    {
        "lib": "pad",
        "mw_version": "GC/1.2.5n",
        "cflags": cflags_sdk,
        "progress_category": "sdk",
        "src_dir": "extern/sdk",
        "objects": [
            Object(NonMatching, "dolphin/pad/pad.c"),
            Object(Matching, "dolphin/pad/PadClamp.c"),
        ],
    },
    {
        "lib": "exi",
        "mw_version": "GC/1.2.5n",
        "cflags": cflags_sdk,
        "progress_category": "sdk",
        "src_dir": "extern/sdk",
        "objects": [
            Object(NonMatching, "dolphin/exi/EXIBios.c"),
            Object(Matching, "dolphin/exi/EXIUart.c"),
        ],
    },
    {
        "lib": "db",
        "mw_version": "GC/1.2.5n",
        "cflags": cflags_sdk,
        "progress_category": "sdk",
        "src_dir": "extern/sdk",
        "objects": [
            Object(Matching, "dolphin/db.c"),
        ],
    },
    {
        "lib": "card",
        "mw_version": "GC/1.2.5n",
        "cflags": cflags_sdk,
        "progress_category": "sdk",
        "src_dir": "extern/sdk",
        "objects": [
            Object(NonMatching, "dolphin/card/CARDBios.c"),
            Object(NonMatching, "dolphin/card/CARDBlock.c"),
            Object(NonMatching, "dolphin/card/CARDDir.c"),
            Object(NonMatching, "dolphin/card/CARDOpen.c"),
            Object(NonMatching, "dolphin/card/CARDStat.c"),
            Object(NonMatching, "dolphin/card/CARDRead.c"),
            Object(Matching, "dolphin/card/CARDWrite.c"),
            Object(Matching, "dolphin/card/CARDMount.c"),
            Object(Matching, "dolphin/card/CARDUnlock.c"),
            Object(Matching, "dolphin/card/CARDCheck.c"),
            Object(Matching, "dolphin/card/CARDCreate.c"),
            Object(Matching, "dolphin/card/CARDDelete.c"),
            Object(Matching, "dolphin/card/CARDFormat.c"),
            Object(Matching, "dolphin/card/CARDRdwr.c"),
            Object(Matching, "dolphin/card/CARDRename.c"),
        ],
    },
    {
        "lib": "dvd",
        "mw_version": "GC/1.2.5n",
        "cflags": cflags_sdk,
        "progress_category": "sdk",
        "src_dir": "extern/sdk",
        "objects": [
            Object(NonMatching, "dolphin/dvd/fstload.c"),
            Object(NonMatching, "dolphin/dvd/dvd.c"),
            Object(NonMatching, "dolphin/dvd/dvdlow.c"),
            Object(NonMatching, "dolphin/dvd/dvdfs.c"),
            Object(Matching, "dolphin/dvd/dvderror.c"),
            Object(Matching, "dolphin/dvd/dvdqueue.c"),
            Object(Matching, "dolphin/dvd/dvdidutils.c"),
        ],
    },
    {
        "lib": "gx",
        "mw_version": "GC/1.2.5n",
        "cflags": cflags_sdk,
        "progress_category": "sdk",
        "src_dir": "extern/sdk",
        "objects": [
            Object(NonMatching, "dolphin/gx/GXPixel.c"),
            Object(NonMatching, "dolphin/gx/GXFifo.c"),
            Object(NonMatching, "dolphin/gx/GXMisc.c"),
            Object(NonMatching, "dolphin/gx/GXTransform.c"),
            Object(NonMatching, "dolphin/gx/GXAttr.c"),
            Object(NonMatching, "dolphin/gx/GXBump.c"),
            Object(NonMatching, "dolphin/gx/GXLight.c"),
            Object(NonMatching, "dolphin/gx/GXTexture.c"),
            Object(Matching, "dolphin/gx/GXInit.c"),
            Object(Matching, "dolphin/gx/GXTev.c"),
            Object(Matching, "dolphin/gx/GXStubs.c"),
            Object(Matching, "dolphin/gx/GXFrameBuf.c"),
            Object(Matching, "dolphin/gx/GXPerf.c"),
            Object(Matching, "dolphin/gx/GXDisplayList.c"),
            Object(Matching, "dolphin/gx/GXGeometry.c"),
        ],
    },
    {
        "lib": "os",
        "mw_version": "GC/1.2.5n",
        "cflags": cflags_sdk,
        "progress_category": "sdk",
        "src_dir": "extern/sdk",
        "objects": [
            Object(NonMatching, "dolphin/os/OSError.c"),
            Object(NonMatching, "dolphin/os/OS.c"),
            Object(NonMatching, "dolphin/os/OSContext.c"),
            Object(NonMatching, "dolphin/os/OSReboot.c"),
            Object(NonMatching, "dolphin/os/OSThread.c"),
            Object(NonMatching, "dolphin/os/OSAlarm.c"),
            Object(NonMatching, "dolphin/os/OSArena.c"),
            Object(NonMatching, "dolphin/os/OSCache.c"),
            Object(NonMatching, "dolphin/os/OSMemory.c"),
            Object(NonMatching, "dolphin/os/OSReset.c"),
            Object(NonMatching, "dolphin/os/OSRtc.c"),
            Object(NonMatching, "dolphin/os/OSTime.c"),
            Object(NonMatching, "dolphin/PPCArch.c"),
            Object(Matching, "dolphin/os/OSResetSW.c"),
            Object(Matching, "dolphin/os/OSInterrupt.c"),
            Object(Matching, "dolphin/os/OSAudioSystem.c"),
            Object(NonMatching, "dolphin/os/OSMutex.c"),
            Object(Matching, "dolphin/os/OSSync.c"),
            Object(Matching, "dolphin/os/__start.c"),
        ],
    },
    {
        "lib": "MSL_C.PPCEABI.bare.H",
        "mw_version": "GC/1.3",
        "cflags": cflags_runtime,
        "progress_category": "sdk",
        "src_dir": "extern/sdk",
        "objects": [
            Object(NonMatching, "runtime/ansi_fp.c"),
            Object(NonMatching, "runtime/printf.c"),
            Object(NonMatching, "runtime/string.c"),
            Object(NonMatching, "runtime/runtime.c"),
            Object(NonMatching, "runtime/ansi_files.c"),
            Object(NonMatching, "runtime/direct_io.c"),
            Object(NonMatching, "runtime/file_io.c"),
            Object(NonMatching, "runtime/FILE_POS.c"),
            Object(Matching, "runtime/ctype.c"),
            Object(Matching, "runtime/e_acos.c"),
            Object(Matching, "runtime/e_asin.c"),
            Object(Matching, "runtime/e_atan2.c"),
            Object(Matching, "runtime/e_fmod.c"),
            Object(Matching, "runtime/e_log.c"),
            Object(Matching, "runtime/e_rem_pio2.c"),
            Object(Matching, "runtime/k_cos.c"),
            Object(Matching, "runtime/k_rem_pio2.c"),
            Object(Matching, "runtime/k_sin.c"),
            Object(Matching, "runtime/k_tan.c"),
            Object(Matching, "runtime/s_cos.c"),
            Object(Matching, "runtime/s_floor.c"),
            Object(Matching, "runtime/s_frexp.c"),
            Object(Matching, "runtime/s_ldexp.c"),
            Object(Matching, "runtime/s_sin.c"),
            Object(Matching, "runtime/s_tan.c"),
            Object(Matching, "runtime/__mem.c"),
            Object(Matching, "runtime/__va_arg.c"),
            Object(Matching, "runtime/buffer_io.c"),
            Object(Matching, "runtime/mem.c"),
            Object(Matching, "runtime/misc_io.c"),
            Object(Matching, "runtime/s_copysign.c"),
            Object(Matching, "runtime/s_modf.c"),
            Object(Matching, "runtime/sscanf.c"),
            Object(Matching, "runtime/wchar_io.c"),
        ],
    },
    {
        # EA game code whose original source file is not yet known.
        "lib": "unsorted",
        "mw_version": "GC/2.5",
        "cflags": cflags_base,
        "progress_category": "game",
        "objects": [
            Object(Matching, "unsorted/code_80007BC4.c"),
            Object(Matching, "unsorted/code_800080D0.c"),
            Object(Matching, "unsorted/code_800082F8.c"),
            Object(NonMatching, "UStream.c"),
            Object(NonMatching, "Golfer.c"),
            Object(NonMatching, "Ball.c"),
            Object(NonMatching, "Swing.c"),
            Object(NonMatching, "CharClip.c"),
            Object(NonMatching, "skalib.c"),
            Object(NonMatching, "CharAnim.c"),
            Object(NonMatching, "HoleScore.c"),
            Object(NonMatching, "Gimme.c"),
            Object(Matching, "unsorted/sweep_8000C0F0.c"),
            Object(Matching, "unsorted/sweep_800B9A88.c"),
            Object(Matching, "unsorted/sweep_800E3ECC.c"),
            Object(Matching, "unsorted/sweep_800E50FC.c"),
            Object(Matching, "unsorted/sweep_8007FF3C.c"),
            Object(Matching, "unsorted/sweep_80080AD0.c"),
            Object(Matching, "unsorted/sweep_80080C60.c"),
            Object(Matching, "unsorted/sweep_80005580.c"),
            Object(Matching, "unsorted/sweep_8000BEC8.c"),
            Object(Matching, "unsorted/sweep_8000BF8C.c"),
            Object(Matching, "unsorted/sweep_8000C244.c"),
            Object(Matching, "unsorted/sweep_8000C5FC.c"),
            Object(Matching, "unsorted/sweep_8001052C.c"),
            Object(Matching, "unsorted/sweep_8001256C.c"),
            Object(Matching, "unsorted/sweep_80015324.c"),
            Object(Matching, "unsorted/sweep_800153BC.c"),
            Object(Matching, "unsorted/sweep_80015454.c"),
            Object(Matching, "unsorted/sweep_8001D624.c"),
            Object(Matching, "unsorted/sweep_8001D6D8.c"),
            Object(Matching, "unsorted/sweep_8001EE98.c"),
            Object(Matching, "unsorted/sweep_80031E40.c"),
            Object(Matching, "unsorted/sweep_80035338.c"),
            Object(Matching, "unsorted/sweep_8003D0A0.c"),
            Object(Matching, "unsorted/sweep_80063C7C.c"),
            Object(Matching, "unsorted/sweep_8006F4E0.c"),
            Object(Matching, "unsorted/sweep_8006F608.c"),
            Object(Matching, "unsorted/sweep_800757B8.c"),
            Object(Matching, "unsorted/sweep_80076090.c"),
            Object(Matching, "unsorted/sweep_80077148.c"),
            Object(Matching, "unsorted/sweep_8007C79C.c"),
            Object(Matching, "unsorted/sweep_8007D9D0.c"),
            Object(Matching, "unsorted/sweep_8007DAB0.c"),
            Object(Matching, "unsorted/sweep_8007E92C.c"),
            Object(Matching, "unsorted/sweep_8007EE80.c"),
            Object(Matching, "unsorted/sweep_80081F98.c"),
            Object(Matching, "unsorted/sweep_80082608.c"),
            Object(Matching, "unsorted/sweep_8008266C.c"),
            Object(Matching, "unsorted/sweep_80084E7C.c"),
            Object(Matching, "unsorted/sweep_8008E244.c"),
            Object(Matching, "unsorted/sweep_8008E924.c"),
            Object(Matching, "unsorted/sweep_8008F80C.c"),
            Object(Matching, "unsorted/sweep_80094278.c"),
            Object(Matching, "unsorted/sweep_8009637C.c"),
            Object(Matching, "unsorted/sweep_80098C70.c"),
            Object(Matching, "unsorted/sweep_8009AA18.c"),
            Object(Matching, "unsorted/sweep_800A2BA8.c"),
            Object(Matching, "unsorted/sweep_800AA498.c"),
            Object(Matching, "unsorted/sweep_800AB374.c"),
            Object(Matching, "unsorted/sweep_800B2724.c"),
            Object(Matching, "unsorted/sweep_800B4BB8.c"),
            Object(Matching, "unsorted/sweep_800B9930.c"),
            Object(Matching, "unsorted/sweep_800BA080.c"),
            Object(Matching, "unsorted/sweep_800BB1F8.c"),
            Object(Matching, "unsorted/sweep_800C44CC.c"),
            Object(Matching, "unsorted/sweep_800C6604.c"),
            Object(Matching, "unsorted/sweep_800D4EF8.c"),
            Object(Matching, "unsorted/sweep_800EE064.c"),
            Object(Matching, "unsorted/sweep_80101CC4.c"),
            Object(Matching, "unsorted/sweep_80108300.c"),
            Object(Matching, "unsorted/sweep_80109500.c"),
            Object(Matching, "unsorted/sweep_8010BEC4.c"),
            Object(Matching, "unsorted/sweep_8010F7C0.c"),
            Object(Matching, "unsorted/sweep_8010F7E4.c"),
            Object(Matching, "unsorted/sweep_8010F880.c"),
            Object(Matching, "unsorted/sweep_801109FC.c"),
            Object(Matching, "unsorted/sweep_80110A24.c"),
            Object(Matching, "unsorted/sweep_8011C580.c"),
            Object(Matching, "unsorted/sweep_8011C59C.c"),
            Object(Matching, "unsorted/sweep_8011FDC4.c"),
            Object(Matching, "unsorted/sweep_801218DC.c"),
            Object(Matching, "unsorted/sweep_80122468.c"),
            Object(Matching, "unsorted/sweep_800136C4.c"),
            Object(Matching, "unsorted/sweep_80048AC4.c"),
            Object(Matching, "unsorted/sweep_8004ABA4.c"),
            Object(Matching, "unsorted/sweep_8006AA70.c"),
            Object(Matching, "unsorted/sweep_800A2604.c"),
            Object(Matching, "unsorted/sweep_800EFE60.c"),
            Object(Matching, "unsorted/sweep_800F3654.c"),
            Object(Matching, "unsorted/sweep_800354C4.c"),
            Object(Matching, "unsorted/sweep_800354E4.c"),
            Object(Matching, "unsorted/sweep_800F194C.c"),
            Object(Matching, "unsorted/sweep_80006DD0.c"),
            Object(Matching, "unsorted/sweep_80006EC8.c"),
            Object(Matching, "unsorted/sweep_80008EF0.c"),
            Object(Matching, "unsorted/sweep_8000C594.c"),
            Object(Matching, "unsorted/sweep_800106C4.c"),
            Object(Matching, "unsorted/sweep_800107E4.c"),
            Object(Matching, "unsorted/sweep_80012550.c"),
            Object(Matching, "unsorted/sweep_80012EC4.c"),
            Object(Matching, "unsorted/sweep_80016CB8.c"),
            Object(Matching, "unsorted/sweep_80016CFC.c"),
            Object(Matching, "unsorted/sweep_80016E28.c"),
            Object(Matching, "unsorted/sweep_800172B4.c"),
            Object(Matching, "unsorted/sweep_80017314.c"),
            Object(Matching, "unsorted/sweep_8001EDF4.c"),
            Object(Matching, "unsorted/sweep_80026B34.c"),
            Object(Matching, "unsorted/sweep_800301F4.c"),
            Object(Matching, "unsorted/sweep_80030214.c"),
            Object(Matching, "unsorted/sweep_800336E4.c"),
            Object(Matching, "unsorted/sweep_80035508.c"),
            Object(Matching, "unsorted/sweep_80035554.c"),
            Object(Matching, "unsorted/sweep_8003CBD4.c"),
            Object(Matching, "unsorted/sweep_8004560C.c"),
            Object(Matching, "unsorted/sweep_80045F50.c"),
            Object(Matching, "unsorted/sweep_800484E0.c"),
            Object(Matching, "unsorted/sweep_8006BF4C.c"),
            Object(Matching, "unsorted/sweep_8006C630.c"),
            Object(Matching, "unsorted/sweep_80070B50.c"),
            Object(Matching, "unsorted/sweep_80070D7C.c"),
            Object(Matching, "unsorted/sweep_80070FB0.c"),
            Object(Matching, "unsorted/sweep_8007325C.c"),
            Object(Matching, "unsorted/sweep_80074CEC.c"),
            Object(Matching, "unsorted/sweep_80075250.c"),
            Object(Matching, "unsorted/sweep_80076E18.c"),
            Object(Matching, "unsorted/sweep_8007C17C.c"),
            Object(Matching, "unsorted/sweep_8007C988.c"),
            Object(Matching, "unsorted/sweep_8007D924.c"),
            Object(Matching, "unsorted/sweep_8007DAD4.c"),
            Object(Matching, "unsorted/sweep_8007E0BC.c"),
            Object(Matching, "unsorted/sweep_8007E8C4.c"),
            Object(Matching, "unsorted/sweep_8007E9A8.c"),
            Object(Matching, "unsorted/sweep_8007FCC0.c"),
            Object(Matching, "unsorted/sweep_8007FED8.c"),
            Object(Matching, "unsorted/sweep_800801C0.c"),
            Object(Matching, "unsorted/sweep_80082928.c"),
            Object(Matching, "unsorted/sweep_80083480.c"),
            Object(Matching, "unsorted/sweep_80086378.c"),
            Object(Matching, "unsorted/sweep_80087E80.c"),
            Object(Matching, "unsorted/sweep_80089B78.c"),
            Object(Matching, "unsorted/sweep_8008B850.c"),
            Object(Matching, "unsorted/sweep_8008B990.c"),
            Object(Matching, "unsorted/sweep_8008E358.c"),
            Object(Matching, "unsorted/sweep_8008E44C.c"),
            Object(Matching, "unsorted/sweep_800988CC.c"),
            Object(Matching, "unsorted/sweep_8009F834.c"),
            Object(Matching, "unsorted/sweep_800A402C.c"),
            Object(Matching, "unsorted/sweep_800A85FC.c"),
            Object(Matching, "unsorted/sweep_800A87A4.c"),
            Object(Matching, "unsorted/sweep_800A8D54.c"),
            Object(Matching, "unsorted/sweep_800A955C.c"),
            Object(Matching, "unsorted/sweep_800AAEEC.c"),
            Object(Matching, "unsorted/sweep_800ACEC4.c"),
            Object(Matching, "unsorted/sweep_800B223C.c"),
            Object(Matching, "unsorted/sweep_800B58B4.c"),
            Object(Matching, "unsorted/sweep_800BB1A8.c"),
            Object(Matching, "unsorted/sweep_800C72DC.c"),
            Object(Matching, "unsorted/sweep_800CD7CC.c"),
            Object(Matching, "unsorted/sweep_800D27CC.c"),
            Object(Matching, "unsorted/sweep_800D2ABC.c"),
            Object(Matching, "unsorted/sweep_800D995C.c"),
            Object(Matching, "unsorted/sweep_800D9E00.c"),
            Object(Matching, "unsorted/sweep_800DAD1C.c"),
            Object(Matching, "unsorted/sweep_800DAF74.c"),
            Object(Matching, "unsorted/sweep_800DC514.c"),
            Object(Matching, "unsorted/sweep_800DCB74.c"),
            Object(Matching, "unsorted/sweep_800DCBA8.c"),
            Object(Matching, "unsorted/sweep_800E27A8.c"),
            Object(Matching, "unsorted/sweep_800E522C.c"),
            Object(Matching, "unsorted/sweep_800E5714.c"),
            Object(Matching, "unsorted/sweep_800E572C.c"),
            Object(Matching, "unsorted/sweep_800E5D90.c"),
            Object(Matching, "unsorted/sweep_800E8114.c"),
            Object(Matching, "unsorted/sweep_800E81A0.c"),
            Object(Matching, "unsorted/sweep_800EFDFC.c"),
            Object(Matching, "unsorted/sweep_800F0E20.c"),
            Object(Matching, "unsorted/sweep_800F0EA0.c"),
            Object(Matching, "unsorted/sweep_800F0EF4.c"),
            Object(Matching, "unsorted/sweep_800F4B00.c"),
            Object(Matching, "unsorted/sweep_800F81EC.c"),
            Object(Matching, "unsorted/sweep_800FF60C.c"),
            Object(Matching, "unsorted/sweep_80102A44.c"),
            Object(Matching, "unsorted/sweep_80104F68.c"),
            Object(Matching, "unsorted/sweep_80105140.c"),
            Object(Matching, "unsorted/sweep_80105C30.c"),
            Object(Matching, "unsorted/sweep_8010C718.c"),
            Object(Matching, "unsorted/sweep_80113764.c"),
            Object(Matching, "unsorted/sweep_801138D8.c"),
            Object(Matching, "unsorted/sweep_801138EC.c"),
            Object(Matching, "unsorted/sweep_80117628.c"),
            Object(Matching, "unsorted/sweep_80117DE8.c"),
            Object(Matching, "unsorted/sweep_80118A4C.c"),
            Object(Matching, "unsorted/sweep_80119028.c"),
            Object(Matching, "unsorted/sweep_8011D09C.c"),
            Object(Matching, "unsorted/sweep_8012022C.c"),
            Object(Matching, "unsorted/sweep_8012028C.c"),
            Object(Matching, "unsorted/sweep_80124A98.c"),
            Object(Matching, "unsorted/sweep_8012566C.c"),
            Object(Matching, "unsorted/sweep_80126F84.c"),
            Object(Matching, "unsorted/sweep_80126FA0.c"),
            Object(Matching, "unsorted/sweep_80137200.c"),
            Object(Matching, "unsorted/sweep_8000BA14.c"),
            Object(Matching, "unsorted/sweep_8000BA6C.c"),
            Object(Matching, "unsorted/sweep_8000C5A4.c"),
            Object(Matching, "unsorted/sweep_80010114.c"),
            Object(Matching, "unsorted/sweep_800102B4.c"),
            Object(Matching, "unsorted/sweep_8001247C.c"),
            Object(Matching, "unsorted/sweep_80012C30.c"),
            Object(Matching, "unsorted/sweep_80016124.c"),
            Object(Matching, "unsorted/sweep_8001A7C8.c"),
            Object(Matching, "unsorted/sweep_8001CE34.c"),
            Object(Matching, "unsorted/sweep_8001D268.c"),
            Object(Matching, "unsorted/sweep_8001D47C.c"),
            Object(Matching, "unsorted/sweep_8001EE64.c"),
            Object(Matching, "unsorted/sweep_8001FAD8.c"),
            Object(Matching, "unsorted/sweep_8001FCA8.c"),
            Object(Matching, "unsorted/sweep_80027740.c"),
            Object(Matching, "unsorted/sweep_8003001C.c"),
            Object(Matching, "unsorted/sweep_80035440.c"),
            Object(Matching, "unsorted/sweep_800644CC.c"),
            Object(Matching, "unsorted/sweep_80064F54.c"),
            Object(Matching, "unsorted/sweep_80065CB8.c"),
            Object(Matching, "unsorted/sweep_80065E70.c"),
            Object(Matching, "unsorted/sweep_80066A14.c"),
            Object(Matching, "unsorted/sweep_80066F30.c"),
            Object(Matching, "unsorted/sweep_80067004.c"),
            Object(Matching, "unsorted/sweep_800676E8.c"),
            Object(Matching, "unsorted/sweep_8006FED4.c"),
            Object(Matching, "unsorted/sweep_80070B78.c"),
            Object(Matching, "unsorted/sweep_80070C24.c"),
            Object(Matching, "unsorted/sweep_80070CD0.c"),
            Object(Matching, "unsorted/sweep_80070D88.c"),
            Object(Matching, "unsorted/sweep_80070F00.c"),
            Object(Matching, "unsorted/sweep_80070FBC.c"),
            Object(Matching, "unsorted/sweep_80071148.c"),
            Object(Matching, "unsorted/sweep_80071578.c"),
            Object(Matching, "unsorted/sweep_80071628.c"),
            Object(Matching, "unsorted/sweep_80076F58.c"),
            Object(Matching, "unsorted/sweep_8007E51C.c"),
            Object(Matching, "unsorted/sweep_80082CA8.c"),
            Object(Matching, "unsorted/sweep_8008422C.c"),
            Object(Matching, "unsorted/sweep_800882F4.c"),
            Object(Matching, "unsorted/sweep_8008AC4C.c"),
            Object(Matching, "unsorted/sweep_8009A3D0.c"),
            Object(Matching, "unsorted/sweep_800A26D8.c"),
            Object(Matching, "unsorted/sweep_800A298C.c"),
            Object(Matching, "unsorted/sweep_800A624C.c"),
            Object(Matching, "unsorted/sweep_800A7720.c"),
            Object(Matching, "unsorted/sweep_800A87B4.c"),
            Object(Matching, "unsorted/sweep_800B06CC.c"),
            Object(Matching, "unsorted/sweep_800B1644.c"),
            Object(Matching, "unsorted/sweep_800B208C.c"),
            Object(Matching, "unsorted/sweep_800B2250.c"),
            Object(Matching, "unsorted/sweep_800B6924.c"),
            Object(Matching, "unsorted/sweep_800BD83C.c"),
            Object(Matching, "unsorted/sweep_800C3EB8.c"),
            Object(Matching, "unsorted/sweep_800CEDE0.c"),
            Object(Matching, "unsorted/sweep_800D3424.c"),
            Object(Matching, "unsorted/sweep_800E1788.c"),
            Object(Matching, "unsorted/sweep_800E4F88.c"),
            Object(Matching, "unsorted/sweep_800E5200.c"),
            Object(Matching, "unsorted/sweep_800E53C0.c"),
            Object(Matching, "unsorted/sweep_800E54A0.c"),
            Object(Matching, "unsorted/sweep_800E5D40.c"),
            Object(Matching, "unsorted/sweep_800ED710.c"),
            Object(Matching, "unsorted/sweep_800F2958.c"),
            Object(Matching, "unsorted/sweep_800F39CC.c"),
            Object(Matching, "unsorted/sweep_800F80D4.c"),
            Object(Matching, "unsorted/sweep_800FDFC4.c"),
            Object(Matching, "unsorted/sweep_800FE02C.c"),
            Object(Matching, "unsorted/sweep_80101F18.c"),
            Object(Matching, "unsorted/sweep_80101F94.c"),
            Object(Matching, "unsorted/sweep_80102354.c"),
            Object(Matching, "unsorted/sweep_80108904.c"),
            Object(Matching, "unsorted/sweep_801089DC.c"),
            Object(Matching, "unsorted/sweep_80109618.c"),
            Object(Matching, "unsorted/sweep_8010A208.c"),
            Object(Matching, "unsorted/sweep_8010D428.c"),
            Object(Matching, "unsorted/sweep_801127A0.c"),
            Object(Matching, "unsorted/sweep_801128C8.c"),
            Object(Matching, "unsorted/sweep_80112A10.c"),
            Object(Matching, "unsorted/sweep_8011368C.c"),
            Object(Matching, "unsorted/sweep_80116F80.c"),
            Object(Matching, "unsorted/sweep_8011766C.c"),
            Object(Matching, "unsorted/sweep_8011B13C.c"),
            Object(Matching, "unsorted/sweep_8011B1AC.c"),
            Object(Matching, "unsorted/sweep_8011B234.c"),
            Object(Matching, "unsorted/sweep_8011B2C4.c"),
            Object(Matching, "unsorted/sweep_8011B3B8.c"),
            Object(Matching, "unsorted/sweep_8011B56C.c"),
            Object(Matching, "unsorted/sweep_80122128.c"),
            Object(Matching, "unsorted/sweep_80124A70.c"),
            Object(Matching, "unsorted/sweep_801255C4.c"),
            Object(Matching, "unsorted/sweep_800055D4.c"),
            Object(Matching, "unsorted/sweep_80005BC8.c"),
            Object(Matching, "unsorted/sweep_800060DC.c"),
            Object(Matching, "unsorted/sweep_800072E0.c"),
            Object(Matching, "unsorted/sweep_80007320.c"),
            Object(Matching, "unsorted/sweep_800073A8.c"),
            Object(Matching, "unsorted/sweep_80009918.c"),
            Object(Matching, "unsorted/sweep_8000AF1C.c"),
            Object(Matching, "unsorted/sweep_8000AF58.c"),
            Object(Matching, "unsorted/sweep_8000B058.c"),
            Object(Matching, "unsorted/sweep_8000B244.c"),
            Object(Matching, "unsorted/sweep_8000B30C.c"),
            Object(Matching, "unsorted/sweep_8000B4B0.c"),
            Object(Matching, "unsorted/sweep_8000BED8.c"),
            Object(Matching, "unsorted/sweep_8000F0E8.c"),
            Object(Matching, "unsorted/sweep_8000FB88.c"),
            Object(Matching, "unsorted/sweep_80010754.c"),
            Object(Matching, "unsorted/sweep_800107C0.c"),
            Object(Matching, "unsorted/sweep_80011160.c"),
            Object(Matching, "unsorted/sweep_80011C8C.c"),
            Object(Matching, "unsorted/sweep_80012438.c"),
            Object(Matching, "unsorted/sweep_80012520.c"),
            Object(Matching, "unsorted/sweep_80012E1C.c"),
            Object(Matching, "unsorted/sweep_80012E4C.c"),
            Object(Matching, "unsorted/sweep_80012FA0.c"),
            Object(Matching, "unsorted/sweep_800137B0.c"),
            Object(Matching, "unsorted/sweep_800142A4.c"),
            Object(Matching, "unsorted/sweep_80014524.c"),
            Object(Matching, "unsorted/sweep_80014590.c"),
            Object(Matching, "unsorted/sweep_80014A60.c"),
            Object(Matching, "unsorted/sweep_80014DF8.c"),
            Object(Matching, "unsorted/sweep_80015464.c"),
            Object(Matching, "unsorted/sweep_80015620.c"),
            Object(Matching, "unsorted/sweep_8001614C.c"),
            Object(Matching, "unsorted/sweep_8001618C.c"),
            Object(Matching, "unsorted/sweep_80016CF4.c"),
            Object(Matching, "unsorted/sweep_80016D10.c"),
            Object(Matching, "unsorted/sweep_8001731C.c"),
            Object(Matching, "unsorted/sweep_80019648.c"),
            Object(Matching, "unsorted/sweep_8001A484.c"),
            Object(Matching, "unsorted/sweep_8001A73C.c"),
            Object(Matching, "unsorted/sweep_8001B1E8.c"),
            Object(Matching, "unsorted/sweep_8001C2E4.c"),
            Object(Matching, "unsorted/sweep_8001C7FC.c"),
            Object(Matching, "unsorted/sweep_8001EFFC.c"),
            Object(Matching, "unsorted/sweep_8001F084.c"),
            Object(Matching, "unsorted/sweep_8001F558.c"),
            Object(Matching, "unsorted/sweep_8001FCD4.c"),
            Object(Matching, "unsorted/sweep_80021978.c"),
            Object(Matching, "unsorted/sweep_80027738.c"),
            Object(Matching, "unsorted/sweep_8002955C.c"),
            Object(Matching, "unsorted/sweep_80029948.c"),
            Object(Matching, "unsorted/sweep_80029A74.c"),
            Object(Matching, "unsorted/sweep_80029A88.c"),
            Object(Matching, "unsorted/sweep_8002A020.c"),
            Object(Matching, "unsorted/sweep_8002A3A4.c"),
            Object(Matching, "unsorted/sweep_8002A624.c"),
            Object(Matching, "unsorted/sweep_8002FEAC.c"),
            Object(Matching, "unsorted/sweep_8002FF94.c"),
            Object(Matching, "unsorted/sweep_8003009C.c"),
            Object(Matching, "unsorted/sweep_8003020C.c"),
            Object(Matching, "unsorted/sweep_8003024C.c"),
            Object(Matching, "unsorted/sweep_8003534C.c"),
            Object(Matching, "unsorted/sweep_8003541C.c"),
            Object(Matching, "unsorted/sweep_80035500.c"),
            Object(Matching, "unsorted/sweep_8003556C.c"),
            Object(Matching, "unsorted/sweep_80035584.c"),
            Object(Matching, "unsorted/sweep_80035600.c"),
            Object(Matching, "unsorted/sweep_80035F1C.c"),
            Object(Matching, "unsorted/sweep_8003612C.c"),
            Object(Matching, "unsorted/sweep_80036460.c"),
            Object(Matching, "unsorted/sweep_800364A0.c"),
            Object(Matching, "unsorted/sweep_80038A6C.c"),
            Object(Matching, "unsorted/sweep_8003944C.c"),
            Object(Matching, "unsorted/sweep_80045D5C.c"),
            Object(Matching, "unsorted/sweep_80045F6C.c"),
            Object(Matching, "unsorted/sweep_80046264.c"),
            Object(Matching, "unsorted/sweep_80048584.c"),
            Object(Matching, "unsorted/sweep_80048804.c"),
            Object(Matching, "unsorted/sweep_80048894.c"),
            Object(Matching, "unsorted/sweep_80048E44.c"),
            Object(Matching, "unsorted/sweep_8004ABB4.c"),
            Object(Matching, "unsorted/sweep_8004AF28.c"),
            Object(Matching, "unsorted/sweep_8004B580.c"),
            Object(Matching, "unsorted/sweep_8004B65C.c"),
            Object(Matching, "unsorted/sweep_800642B0.c"),
            Object(Matching, "unsorted/sweep_80065B44.c"),
            Object(Matching, "unsorted/sweep_80065B98.c"),
            Object(Matching, "unsorted/sweep_80065D6C.c"),
            Object(Matching, "unsorted/sweep_80065E98.c"),
            Object(Matching, "unsorted/sweep_800676AC.c"),
            Object(Matching, "unsorted/sweep_80069498.c"),
            Object(Matching, "unsorted/sweep_8006DD84.c"),
            Object(Matching, "unsorted/sweep_8006E0F8.c"),
            Object(Matching, "unsorted/sweep_8006E214.c"),
            Object(Matching, "unsorted/sweep_8006F430.c"),
            Object(Matching, "unsorted/sweep_8006F4F0.c"),
            Object(Matching, "unsorted/sweep_8006F64C.c"),
            Object(Matching, "unsorted/sweep_8006FFD4.c"),
            Object(Matching, "unsorted/sweep_80070168.c"),
            Object(Matching, "unsorted/sweep_80070B74.c"),
            Object(Matching, "unsorted/sweep_80071574.c"),
            Object(Matching, "unsorted/sweep_80071624.c"),
            Object(Matching, "unsorted/sweep_800718C4.c"),
            Object(Matching, "unsorted/sweep_8007524C.c"),
            Object(Matching, "unsorted/sweep_80076088.c"),
            Object(Matching, "unsorted/sweep_8007644C.c"),
            Object(Matching, "unsorted/sweep_80076B18.c"),
            Object(Matching, "unsorted/sweep_80076F20.c"),
            Object(Matching, "unsorted/sweep_80076F54.c"),
            Object(Matching, "unsorted/sweep_80077428.c"),
            Object(Matching, "unsorted/sweep_8007BD18.c"),
            Object(Matching, "unsorted/sweep_8007BEEC.c"),
            Object(Matching, "unsorted/sweep_8007C248.c"),
            Object(Matching, "unsorted/sweep_8007C488.c"),
            Object(Matching, "unsorted/sweep_8007C7AC.c"),
            Object(Matching, "unsorted/sweep_8007C94C.c"),
            Object(Matching, "unsorted/sweep_8007CDF0.c"),
            Object(Matching, "unsorted/sweep_8007CE1C.c"),
            Object(Matching, "unsorted/sweep_8007CE58.c"),
            Object(Matching, "unsorted/sweep_8007D2D0.c"),
            Object(Matching, "unsorted/sweep_8007D3B4.c"),
            Object(Matching, "unsorted/sweep_8007D964.c"),
            Object(Matching, "unsorted/sweep_8007DAD0.c"),
            Object(Matching, "unsorted/sweep_8007E200.c"),
            Object(Matching, "unsorted/sweep_8007E288.c"),
            Object(Matching, "unsorted/sweep_8007E354.c"),
            Object(Matching, "unsorted/sweep_8007E798.c"),
            Object(Matching, "unsorted/sweep_8007EE7C.c"),
            Object(Matching, "unsorted/sweep_8007EF9C.c"),
            Object(Matching, "unsorted/sweep_80080300.c"),
            Object(Matching, "unsorted/sweep_800804D8.c"),
            Object(Matching, "unsorted/sweep_800805F0.c"),
            Object(Matching, "unsorted/sweep_800807D0.c"),
            Object(Matching, "unsorted/sweep_80081BD4.c"),
            Object(Matching, "unsorted/sweep_80081CF8.c"),
            Object(Matching, "unsorted/sweep_8008281C.c"),
            Object(Matching, "unsorted/sweep_800829EC.c"),
            Object(Matching, "unsorted/sweep_80082CA4.c"),
            Object(Matching, "unsorted/sweep_80083354.c"),
            Object(Matching, "unsorted/sweep_800834DC.c"),
            Object(Matching, "unsorted/sweep_80083970.c"),
            Object(Matching, "unsorted/sweep_80083BA4.c"),
            Object(Matching, "unsorted/sweep_80083F54.c"),
            Object(Matching, "unsorted/sweep_80084208.c"),
            Object(Matching, "unsorted/sweep_80084288.c"),
            Object(Matching, "unsorted/sweep_800846C8.c"),
            Object(Matching, "unsorted/sweep_80084750.c"),
            Object(Matching, "unsorted/sweep_800847BC.c"),
            Object(Matching, "unsorted/sweep_800848E4.c"),
            Object(Matching, "unsorted/sweep_80084BE4.c"),
            Object(Matching, "unsorted/sweep_80084F3C.c"),
            Object(Matching, "unsorted/sweep_80084FF0.c"),
            Object(Matching, "unsorted/sweep_80086384.c"),
            Object(Matching, "unsorted/sweep_800866E8.c"),
            Object(Matching, "unsorted/sweep_800874F0.c"),
            Object(Matching, "unsorted/sweep_80087E60.c"),
            Object(Matching, "unsorted/sweep_80088830.c"),
            Object(Matching, "unsorted/sweep_80089584.c"),
            Object(Matching, "unsorted/sweep_800896A8.c"),
            Object(Matching, "unsorted/sweep_800896D0.c"),
            Object(Matching, "unsorted/sweep_80089AD0.c"),
            Object(Matching, "unsorted/sweep_80089CAC.c"),
            Object(Matching, "unsorted/sweep_80089E98.c"),
            Object(Matching, "unsorted/sweep_8008A184.c"),
            Object(Matching, "unsorted/sweep_8008A208.c"),
            Object(Matching, "unsorted/sweep_8008A7C8.c"),
            Object(Matching, "unsorted/sweep_8008A800.c"),
            Object(Matching, "unsorted/sweep_8008A86C.c"),
            Object(Matching, "unsorted/sweep_8008AAAC.c"),
            Object(Matching, "unsorted/sweep_8008AB40.c"),
            Object(Matching, "unsorted/sweep_8008B3C8.c"),
            Object(Matching, "unsorted/sweep_8008B430.c"),
            Object(Matching, "unsorted/sweep_8008B4A0.c"),
            Object(Matching, "unsorted/sweep_8008B570.c"),
            Object(Matching, "unsorted/sweep_8008B5FC.c"),
            Object(Matching, "unsorted/sweep_8008B674.c"),
            Object(Matching, "unsorted/sweep_8008B6E4.c"),
            Object(Matching, "unsorted/sweep_8008C938.c"),
            Object(Matching, "unsorted/sweep_8008D8CC.c"),
            Object(Matching, "unsorted/sweep_8008E354.c"),
            Object(Matching, "unsorted/sweep_8008E718.c"),
            Object(Matching, "unsorted/sweep_8008E818.c"),
            Object(Matching, "unsorted/sweep_8008E918.c"),
            Object(Matching, "unsorted/sweep_8008E938.c"),
            Object(Matching, "unsorted/sweep_8008E9A8.c"),
            Object(Matching, "unsorted/sweep_8008EA38.c"),
            Object(Matching, "unsorted/sweep_8008EC60.c"),
            Object(Matching, "unsorted/sweep_8008F0C0.c"),
            Object(Matching, "unsorted/sweep_8008F0F0.c"),
            Object(Matching, "unsorted/sweep_8008F15C.c"),
            Object(Matching, "unsorted/sweep_8008F18C.c"),
            Object(Matching, "unsorted/sweep_8008F354.c"),
            Object(Matching, "unsorted/sweep_8008F39C.c"),
            Object(Matching, "unsorted/sweep_8008F644.c"),
            Object(Matching, "unsorted/sweep_80090898.c"),
            Object(Matching, "unsorted/sweep_80091454.c"),
            Object(Matching, "unsorted/sweep_80091708.c"),
            Object(Matching, "unsorted/sweep_80091EE4.c"),
            Object(Matching, "unsorted/sweep_8009220C.c"),
            Object(Matching, "unsorted/sweep_800922A0.c"),
            Object(Matching, "unsorted/sweep_800929E0.c"),
            Object(Matching, "unsorted/sweep_80093AD4.c"),
            Object(Matching, "unsorted/sweep_80094274.c"),
            Object(Matching, "unsorted/sweep_80095364.c"),
            Object(Matching, "unsorted/sweep_80097688.c"),
            Object(Matching, "unsorted/sweep_8009A1EC.c"),
            Object(Matching, "unsorted/sweep_8009A340.c"),
            Object(Matching, "unsorted/sweep_8009A704.c"),
            Object(Matching, "unsorted/sweep_8009A968.c"),
            Object(Matching, "unsorted/sweep_8009B894.c"),
            Object(Matching, "unsorted/sweep_8009DCE8.c"),
            Object(Matching, "unsorted/sweep_8009EF90.c"),
            Object(Matching, "unsorted/sweep_8009F7E4.c"),
            Object(Matching, "unsorted/sweep_800A19F4.c"),
            Object(Matching, "unsorted/sweep_800A218C.c"),
            Object(Matching, "unsorted/sweep_800A2628.c"),
            Object(Matching, "unsorted/sweep_800A27F4.c"),
            Object(Matching, "unsorted/sweep_800A2958.c"),
            Object(Matching, "unsorted/sweep_800A3F38.c"),
            Object(Matching, "unsorted/sweep_800A4038.c"),
            Object(Matching, "unsorted/sweep_800A4080.c"),
            Object(Matching, "unsorted/sweep_800A5620.c"),
            Object(Matching, "unsorted/sweep_800A7644.c"),
            Object(Matching, "unsorted/sweep_800A7AD0.c"),
            Object(Matching, "unsorted/sweep_800A8700.c"),
            Object(Matching, "unsorted/sweep_800A874C.c"),
            Object(Matching, "unsorted/sweep_800A87B0.c"),
            Object(Matching, "unsorted/sweep_800A8824.c"),
            Object(Matching, "unsorted/sweep_800A9AC4.c"),
            Object(Matching, "unsorted/sweep_800AA444.c"),
            Object(Matching, "unsorted/sweep_800AA694.c"),
            Object(Matching, "unsorted/sweep_800AAAA0.c"),
            Object(Matching, "unsorted/sweep_800AAD14.c"),
            Object(Matching, "unsorted/sweep_800AADE8.c"),
            Object(Matching, "unsorted/sweep_800AAE70.c"),
            Object(Matching, "unsorted/sweep_800AB39C.c"),
            Object(Matching, "unsorted/sweep_800ABC34.c"),
            Object(Matching, "unsorted/sweep_800AC328.c"),
            Object(Matching, "unsorted/sweep_800AD1C4.c"),
            Object(Matching, "unsorted/sweep_800ADA08.c"),
            Object(Matching, "unsorted/sweep_800AF140.c"),
            Object(Matching, "unsorted/sweep_800AF2D8.c"),
            Object(Matching, "unsorted/sweep_800AFB48.c"),
            Object(Matching, "unsorted/sweep_800B04CC.c"),
            Object(Matching, "unsorted/sweep_800B055C.c"),
            Object(Matching, "unsorted/sweep_800B0954.c"),
            Object(Matching, "unsorted/sweep_800B1608.c"),
            Object(Matching, "unsorted/sweep_800B1AA8.c"),
            Object(Matching, "unsorted/sweep_800B1F9C.c"),
            Object(Matching, "unsorted/sweep_800B235C.c"),
            Object(Matching, "unsorted/sweep_800B246C.c"),
            Object(Matching, "unsorted/sweep_800B352C.c"),
            Object(Matching, "unsorted/sweep_800B3D64.c"),
            Object(Matching, "unsorted/sweep_800B4908.c"),
            Object(Matching, "unsorted/sweep_800B4BFC.c"),
            Object(Matching, "unsorted/sweep_800B5F28.c"),
            Object(Matching, "unsorted/sweep_800B6C0C.c"),
            Object(Matching, "unsorted/sweep_800B6CD0.c"),
            Object(Matching, "unsorted/sweep_800BAA4C.c"),
            Object(Matching, "unsorted/sweep_800BB4B0.c"),
            Object(Matching, "unsorted/sweep_800C4518.c"),
            Object(Matching, "unsorted/sweep_800C6C8C.c"),
            Object(Matching, "unsorted/sweep_800C7080.c"),
            Object(Matching, "unsorted/sweep_800C70F8.c"),
            Object(Matching, "unsorted/sweep_800D1D30.c"),
            Object(Matching, "unsorted/sweep_800D29E8.c"),
            Object(Matching, "unsorted/sweep_800D33F0.c"),
            Object(Matching, "unsorted/sweep_800D7660.c"),
            Object(Matching, "unsorted/sweep_800D9954.c"),
            Object(Matching, "unsorted/sweep_800DCBB8.c"),
            Object(Matching, "unsorted/sweep_800DEA24.c"),
            Object(Matching, "unsorted/sweep_800E177C.c"),
            Object(Matching, "unsorted/sweep_800E3BEC.c"),
            Object(Matching, "unsorted/sweep_800E415C.c"),
            Object(Matching, "unsorted/sweep_800E41C8.c"),
            Object(Matching, "unsorted/sweep_800E45C0.c"),
            Object(Matching, "unsorted/sweep_800E4D88.c"),
            Object(Matching, "unsorted/sweep_800E508C.c"),
            Object(Matching, "unsorted/sweep_800E5110.c"),
            Object(Matching, "unsorted/sweep_800E5228.c"),
            Object(Matching, "unsorted/sweep_800E53E8.c"),
            Object(Matching, "unsorted/sweep_800E5708.c"),
            Object(Matching, "unsorted/sweep_800E5724.c"),
            Object(Matching, "unsorted/sweep_800E5908.c"),
            Object(Matching, "unsorted/sweep_800E5C84.c"),
            Object(Matching, "unsorted/sweep_800E7F68.c"),
            Object(Matching, "unsorted/sweep_800E8904.c"),
            Object(Matching, "unsorted/sweep_800EADD8.c"),
            Object(Matching, "unsorted/sweep_800EAE6C.c"),
            Object(Matching, "unsorted/sweep_800EC550.c"),
            Object(Matching, "unsorted/sweep_800ED9A0.c"),
            Object(Matching, "unsorted/sweep_800EDE78.c"),
            Object(Matching, "unsorted/sweep_800EE470.c"),
            Object(Matching, "unsorted/sweep_800EF294.c"),
            Object(Matching, "unsorted/sweep_800EF834.c"),
            Object(Matching, "unsorted/sweep_800F0818.c"),
            Object(Matching, "unsorted/sweep_800F0E18.c"),
            Object(Matching, "unsorted/sweep_800F102C.c"),
            Object(Matching, "unsorted/sweep_800F1404.c"),
            Object(Matching, "unsorted/sweep_800F2C2C.c"),
            Object(Matching, "unsorted/sweep_800F330C.c"),
            Object(Matching, "unsorted/sweep_800F37F8.c"),
            Object(Matching, "unsorted/sweep_800F3C74.c"),
            Object(Matching, "unsorted/sweep_800F4698.c"),
            Object(Matching, "unsorted/sweep_800F4DB4.c"),
            Object(Matching, "unsorted/sweep_800F577C.c"),
            Object(Matching, "unsorted/sweep_800F5A88.c"),
            Object(Matching, "unsorted/sweep_800F5D10.c"),
            Object(Matching, "unsorted/sweep_800F673C.c"),
            Object(Matching, "unsorted/sweep_800F6A00.c"),
            Object(Matching, "unsorted/sweep_800F6D0C.c"),
            Object(Matching, "unsorted/sweep_800F7C00.c"),
            Object(Matching, "unsorted/sweep_800F7ED8.c"),
            Object(Matching, "unsorted/sweep_800F80A0.c"),
            Object(Matching, "unsorted/sweep_800F9824.c"),
            Object(Matching, "unsorted/sweep_800F9BF8.c"),
            Object(Matching, "unsorted/sweep_800FA2C8.c"),
            Object(Matching, "unsorted/sweep_800FA994.c"),
            Object(Matching, "unsorted/sweep_800FD6A0.c"),
            Object(Matching, "unsorted/sweep_800FE8A0.c"),
            Object(Matching, "unsorted/sweep_800FEC78.c"),
            Object(Matching, "unsorted/sweep_800FF604.c"),
            Object(Matching, "unsorted/sweep_800FFDB0.c"),
            Object(Matching, "unsorted/sweep_80100C00.c"),
            Object(Matching, "unsorted/sweep_80101CD8.c"),
            Object(Matching, "unsorted/sweep_80101EDC.c"),
            Object(Matching, "unsorted/sweep_80101F70.c"),
            Object(Matching, "unsorted/sweep_801020BC.c"),
            Object(Matching, "unsorted/sweep_801021FC.c"),
            Object(Matching, "unsorted/sweep_80102308.c"),
            Object(Matching, "unsorted/sweep_801025F4.c"),
            Object(Matching, "unsorted/sweep_80102AC4.c"),
            Object(Matching, "unsorted/sweep_80103BB4.c"),
            Object(Matching, "unsorted/sweep_80105240.c"),
            Object(Matching, "unsorted/sweep_80105C00.c"),
            Object(Matching, "unsorted/sweep_80105EFC.c"),
            Object(Matching, "unsorted/sweep_80107BA4.c"),
            Object(Matching, "unsorted/sweep_80107C30.c"),
            Object(Matching, "unsorted/sweep_801088A4.c"),
            Object(Matching, "unsorted/sweep_801089BC.c"),
            Object(Matching, "unsorted/sweep_80109430.c"),
            Object(Matching, "unsorted/sweep_801094FC.c"),
            Object(Matching, "unsorted/sweep_80109734.c"),
            Object(Matching, "unsorted/sweep_80109760.c"),
            Object(Matching, "unsorted/sweep_80109DDC.c"),
            Object(Matching, "unsorted/sweep_8010A780.c"),
            Object(Matching, "unsorted/sweep_8010AD10.c"),
            Object(Matching, "unsorted/sweep_8010BC64.c"),
            Object(Matching, "unsorted/sweep_8010C714.c"),
            Object(Matching, "unsorted/sweep_8010D230.c"),
            Object(Matching, "unsorted/sweep_8010EF80.c"),
            Object(Matching, "unsorted/sweep_8010F7D8.c"),
            Object(Matching, "unsorted/sweep_8010FBC4.c"),
            Object(Matching, "unsorted/sweep_80110178.c"),
            Object(Matching, "unsorted/sweep_801104A0.c"),
            Object(Matching, "unsorted/sweep_80110A1C.c"),
            Object(Matching, "unsorted/sweep_80112438.c"),
            Object(Matching, "unsorted/sweep_80112964.c"),
            Object(Matching, "unsorted/sweep_80113840.c"),
            Object(Matching, "unsorted/sweep_8011387C.c"),
            Object(Matching, "unsorted/sweep_801138E8.c"),
            Object(Matching, "unsorted/sweep_80113A7C.c"),
            Object(Matching, "unsorted/sweep_80113B14.c"),
            Object(Matching, "unsorted/sweep_80113BAC.c"),
            Object(Matching, "unsorted/sweep_8011407C.c"),
            Object(Matching, "unsorted/sweep_80116DD4.c"),
            Object(Matching, "unsorted/sweep_801170EC.c"),
            Object(Matching, "unsorted/sweep_80117180.c"),
            Object(Matching, "unsorted/sweep_80117DE0.c"),
            Object(Matching, "unsorted/sweep_8011C84C.c"),
            Object(Matching, "unsorted/sweep_8011D858.c"),
            Object(Matching, "unsorted/sweep_8011E3B0.c"),
            Object(Matching, "unsorted/sweep_801202F8.c"),
            Object(Matching, "unsorted/sweep_80120D68.c"),
            Object(Matching, "unsorted/sweep_801213F0.c"),
            Object(Matching, "unsorted/sweep_8012214C.c"),
            Object(Matching, "unsorted/sweep_80122488.c"),
            Object(Matching, "unsorted/sweep_80122630.c"),
            Object(Matching, "unsorted/sweep_80122868.c"),
            Object(Matching, "unsorted/sweep_80124814.c"),
            Object(Matching, "unsorted/sweep_80125520.c"),
            Object(Matching, "unsorted/sweep_801255F8.c"),
            Object(Matching, "unsorted/sweep_80126130.c"),
            Object(Matching, "unsorted/sweep_8012632C.c"),
            Object(Matching, "unsorted/sweep_80126E68.c"),
            Object(Matching, "unsorted/sweep_8012D7F0.c"),
            Object(Matching, "unsorted/sweep_8012E818.c"),
            Object(Matching, "unsorted/sweep_80136064.c"),
            Object(Matching, "unsorted/sweep_80136980.c"),
            Object(Matching, "unsorted/sweep_801369E4.c"),
            Object(Matching, "unsorted/sweep_801372C0.c"),
            Object(Matching, "unsorted/sweep_80137C2C.c"),
            Object(Matching, "unsorted/sweep_8013B3C4.c"),
            Object(Matching, "unsorted/sweep_8013FF30.c"),
            Object(Matching, "unsorted/sweep_80145B1C.c"),
            Object(Matching, "unsorted/sweep_8014CA80.c"),
            Object(Matching, "unsorted/sweep_8015C120.c"),
            Object(Matching, "unsorted/sweep_801654D0.c"),
            Object(Matching, "unsorted/sweep_80165524.c"),
            Object(Matching, "unsorted/sweep_80165C6C.c"),
            Object(Matching, "unsorted/sweep_80169B28.c"),
            Object(Matching, "unsorted/sweep_8000724C.c"),
            Object(Matching, "unsorted/sweep_80008820.c"),
            Object(Matching, "unsorted/sweep_800097C4.c"),
            Object(Matching, "unsorted/sweep_8000A0AC.c"),
            Object(Matching, "unsorted/sweep_8000B3E8.c"),
            Object(Matching, "unsorted/sweep_800106A0.c"),
            Object(Matching, "unsorted/sweep_800124A4.c"),
            Object(Matching, "unsorted/sweep_80012898.c"),
            Object(Matching, "unsorted/sweep_80012ED0.c"),
            Object(Matching, "unsorted/sweep_80013030.c"),
            Object(Matching, "unsorted/sweep_800136F4.c"),
            Object(Matching, "unsorted/sweep_80013D58.c"),
            Object(Matching, "unsorted/sweep_80013E28.c"),
            Object(Matching, "unsorted/sweep_80014134.c"),
            Object(Matching, "unsorted/sweep_8001425C.c"),
            Object(Matching, "unsorted/sweep_80014E68.c"),
            Object(Matching, "unsorted/sweep_800162A0.c"),
            Object(Matching, "unsorted/sweep_8001EE88.c"),
            Object(Matching, "unsorted/sweep_800352E4.c"),
            Object(Matching, "unsorted/sweep_800354B4.c"),
            Object(Matching, "unsorted/sweep_80035FBC.c"),
            Object(Matching, "unsorted/sweep_8003954C.c"),
            Object(Matching, "unsorted/sweep_80045E3C.c"),
            Object(Matching, "unsorted/sweep_80045F14.c"),
            Object(Matching, "unsorted/sweep_800486EC.c"),
            Object(Matching, "unsorted/sweep_8004950C.c"),
            Object(Matching, "unsorted/sweep_800664D8.c"),
            Object(Matching, "unsorted/sweep_80066994.c"),
            Object(Matching, "unsorted/sweep_80066BE8.c"),
            Object(Matching, "unsorted/sweep_80066D54.c"),
            Object(Matching, "unsorted/sweep_80066FA8.c"),
            Object(Matching, "unsorted/sweep_8006752C.c"),
            Object(Matching, "unsorted/sweep_8006A89C.c"),
            Object(Matching, "unsorted/sweep_8006DC34.c"),
            Object(Matching, "unsorted/sweep_8006DCA0.c"),
            Object(Matching, "unsorted/sweep_8006E0A8.c"),
            Object(Matching, "unsorted/sweep_8006E1C0.c"),
            Object(Matching, "unsorted/sweep_8006F144.c"),
            Object(Matching, "unsorted/sweep_8006F5F8.c"),
            Object(Matching, "unsorted/sweep_8006FCC4.c"),
            Object(Matching, "unsorted/sweep_8006FDCC.c"),
            Object(Matching, "unsorted/sweep_800716D4.c"),
            Object(Matching, "unsorted/sweep_80071850.c"),
            Object(Matching, "unsorted/sweep_8007190C.c"),
            Object(Matching, "unsorted/sweep_80071A14.c"),
            Object(Matching, "unsorted/sweep_8007531C.c"),
            Object(Matching, "unsorted/sweep_80075C48.c"),
            Object(Matching, "unsorted/sweep_800760A0.c"),
            Object(Matching, "unsorted/sweep_800763B4.c"),
            Object(Matching, "unsorted/sweep_80076A04.c"),
            Object(Matching, "unsorted/sweep_80076AC4.c"),
            Object(Matching, "unsorted/sweep_8007731C.c"),
            Object(Matching, "unsorted/sweep_8007BCA0.c"),
            Object(Matching, "unsorted/sweep_8007C4B8.c"),
            Object(Matching, "unsorted/sweep_8007C784.c"),
            Object(Matching, "unsorted/sweep_8007D25C.c"),
            Object(Matching, "unsorted/sweep_8007D408.c"),
            Object(Matching, "unsorted/sweep_8007D6D8.c"),
            Object(Matching, "unsorted/sweep_8007DB28.c"),
            Object(Matching, "unsorted/sweep_8007E744.c"),
            Object(Matching, "unsorted/sweep_8007E8B4.c"),
            Object(Matching, "unsorted/sweep_8007E9A0.c"),
            Object(Matching, "unsorted/sweep_80082978.c"),
            Object(Matching, "unsorted/sweep_800829D4.c"),
            Object(Matching, "unsorted/sweep_80082A44.c"),
            Object(Matching, "unsorted/sweep_800833A4.c"),
            Object(Matching, "unsorted/sweep_800835B8.c"),
            Object(Matching, "unsorted/sweep_80083890.c"),
            Object(Matching, "unsorted/sweep_80083904.c"),
            Object(Matching, "unsorted/sweep_80083A44.c"),
            Object(Matching, "unsorted/sweep_80083E70.c"),
            Object(Matching, "unsorted/sweep_80084158.c"),
            Object(Matching, "unsorted/sweep_80084F04.c"),
            Object(Matching, "unsorted/sweep_80087D14.c"),
            Object(Matching, "unsorted/sweep_800880AC.c"),
            Object(Matching, "unsorted/sweep_800881A8.c"),
            Object(Matching, "unsorted/sweep_80088354.c"),
            Object(Matching, "unsorted/sweep_80088634.c"),
            Object(Matching, "unsorted/sweep_8008967C.c"),
            Object(Matching, "unsorted/sweep_80089BD0.c"),
            Object(Matching, "unsorted/sweep_80089D04.c"),
            Object(Matching, "unsorted/sweep_80089D98.c"),
            Object(Matching, "unsorted/sweep_80089E5C.c"),
            Object(Matching, "unsorted/sweep_8008AC3C.c"),
            Object(Matching, "unsorted/sweep_8008B204.c"),
            Object(Matching, "unsorted/sweep_8008EAB0.c"),
            Object(Matching, "unsorted/sweep_80090890.c"),
            Object(Matching, "unsorted/sweep_800908BC.c"),
            Object(Matching, "unsorted/sweep_80092BA0.c"),
            Object(Matching, "unsorted/sweep_80093268.c"),
            Object(Matching, "unsorted/sweep_8009554C.c"),
            Object(Matching, "unsorted/sweep_80098844.c"),
            Object(Matching, "unsorted/sweep_8009B314.c"),
            Object(Matching, "unsorted/sweep_8009B604.c"),
            Object(Matching, "unsorted/sweep_8009CD7C.c"),
            Object(Matching, "unsorted/sweep_8009EB30.c"),
            Object(Matching, "unsorted/sweep_8009F35C.c"),
            Object(Matching, "unsorted/sweep_800A3F94.c"),
            Object(Matching, "unsorted/sweep_800A6448.c"),
            Object(Matching, "unsorted/sweep_800A7924.c"),
            Object(Matching, "unsorted/sweep_800A7994.c"),
            Object(Matching, "unsorted/sweep_800A7C24.c"),
            Object(Matching, "unsorted/sweep_800A86B0.c"),
            Object(Matching, "unsorted/sweep_800A942C.c"),
            Object(Matching, "unsorted/sweep_800AA2EC.c"),
            Object(Matching, "unsorted/sweep_800AC494.c"),
            Object(Matching, "unsorted/sweep_800AF31C.c"),
            Object(Matching, "unsorted/sweep_800B0430.c"),
            Object(Matching, "unsorted/sweep_800B0790.c"),
            Object(Matching, "unsorted/sweep_800B204C.c"),
            Object(Matching, "unsorted/sweep_800B21D0.c"),
            Object(Matching, "unsorted/sweep_800B22D4.c"),
            Object(Matching, "unsorted/sweep_800B4BB0.c"),
            Object(Matching, "unsorted/sweep_800B5C30.c"),
            Object(Matching, "unsorted/sweep_800B655C.c"),
            Object(Matching, "unsorted/sweep_800B7684.c"),
            Object(Matching, "unsorted/sweep_800BB0A8.c"),
            Object(Matching, "unsorted/sweep_800BCD50.c"),
            Object(Matching, "unsorted/sweep_800C7138.c"),
            Object(Matching, "unsorted/sweep_800CCA1C.c"),
            Object(Matching, "unsorted/sweep_800CE164.c"),
            Object(Matching, "unsorted/sweep_800CEE88.c"),
            Object(Matching, "unsorted/sweep_800CEEF4.c"),
            Object(Matching, "unsorted/sweep_800DAD44.c"),
            Object(Matching, "unsorted/sweep_800DCAD8.c"),
            Object(Matching, "unsorted/sweep_800E0A84.c"),
            Object(Matching, "unsorted/sweep_800E3AA0.c"),
            Object(Matching, "unsorted/sweep_800E53A4.c"),
            Object(Matching, "unsorted/sweep_800E542C.c"),
            Object(Matching, "unsorted/sweep_800E7A7C.c"),
            Object(Matching, "unsorted/sweep_800E81B4.c"),
            Object(Matching, "unsorted/sweep_800ED540.c"),
            Object(Matching, "unsorted/sweep_800ED6E8.c"),
            Object(Matching, "unsorted/sweep_800ED8E0.c"),
            Object(Matching, "unsorted/sweep_800EE8B0.c"),
            Object(Matching, "unsorted/sweep_800F193C.c"),
            Object(Matching, "unsorted/sweep_800F2664.c"),
            Object(Matching, "unsorted/sweep_800F3410.c"),
            Object(Matching, "unsorted/sweep_800F475C.c"),
            Object(Matching, "unsorted/sweep_800F5848.c"),
            Object(Matching, "unsorted/sweep_800F59CC.c"),
            Object(Matching, "unsorted/sweep_800F6820.c"),
            Object(Matching, "unsorted/sweep_800F6A34.c"),
            Object(Matching, "unsorted/sweep_800F7D8C.c"),
            Object(Matching, "unsorted/sweep_800FDF38.c"),
            Object(Matching, "unsorted/sweep_801000E8.c"),
            Object(Matching, "unsorted/sweep_80102134.c"),
            Object(Matching, "unsorted/sweep_80103B4C.c"),
            Object(Matching, "unsorted/sweep_80105404.c"),
            Object(Matching, "unsorted/sweep_80107994.c"),
            Object(Matching, "unsorted/sweep_8010988C.c"),
            Object(Matching, "unsorted/sweep_8010A3A4.c"),
            Object(Matching, "unsorted/sweep_8010C73C.c"),
            Object(Matching, "unsorted/sweep_8010C8B8.c"),
            Object(Matching, "unsorted/sweep_8010C934.c"),
            Object(Matching, "unsorted/sweep_8010D32C.c"),
            Object(Matching, "unsorted/sweep_8010F52C.c"),
            Object(Matching, "unsorted/sweep_80110450.c"),
            Object(Matching, "unsorted/sweep_80113E54.c"),
            Object(Matching, "unsorted/sweep_80116540.c"),
            Object(Matching, "unsorted/sweep_801165A0.c"),
            Object(Matching, "unsorted/sweep_8011C054.c"),
            Object(Matching, "unsorted/sweep_8011D268.c"),
            Object(Matching, "unsorted/sweep_8012408C.c"),
            Object(Matching, "unsorted/sweep_801241AC.c"),
            Object(Matching, "unsorted/sweep_80125694.c"),
            Object(Matching, "unsorted/sweep_80125814.c"),
            Object(Matching, "unsorted/sweep_80125910.c"),
            Object(Matching, "unsorted/sweep_801260B8.c"),
            Object(Matching, "unsorted/sweep_80126418.c"),
            Object(Matching, "unsorted/sweep_80126F7C.c"),
            Object(Matching, "unsorted/sweep_8012C83C.c"),
            Object(Matching, "unsorted/sweep_8012CCC0.c"),
            Object(Matching, "unsorted/sweep_801338E0.c"),
            Object(Matching, "unsorted/sweep_80136DF4.c"),
            Object(Matching, "unsorted/sweep_80150F24.c"),
            Object(Matching, "unsorted/sweep_80155F40.c"),
            Object(Matching, "unsorted/sweep_8015F784.c"),
            Object(Matching, "unsorted/sweep_80169B3C.c"),
            Object(Matching, "unsorted/sweep_8016C18C.c"),
        ],
    },
    {
        "lib": "Runtime.PPCEABI.H",
        "mw_version": config.linker_version,
        "cflags": cflags_runtime,
        "progress_category": "sdk",  # str | List[str]
        "objects": [
            Object(NonMatching, "Runtime.PPCEABI.H/global_destructor_chain.c"),
            Object(NonMatching, "Runtime.PPCEABI.H/__init_cpp_exceptions.cpp"),
        ],
    },
]


# Optional callback to adjust link order. This can be used to add, remove, or reorder objects.
# This is called once per module, with the module ID and the current link order.
#
# For example, this adds "dummy.c" to the end of the DOL link order if configured with --non-matching.
# "dummy.c" *must* be configured as a Matching (or Equivalent) object in order to be linked.
def link_order_callback(module_id: int, objects: List[str]) -> List[str]:
    # Don't modify the link order for matching builds
    if not config.non_matching:
        return objects
    if module_id == 0:  # DOL
        return objects + ["dummy.c"]
    return objects


# Uncomment to enable the link order callback.
# config.link_order_callback = link_order_callback


# Optional extra categories for progress tracking
# Adjust as desired for your project
config.progress_categories = [
    ProgressCategory("game", "Game Code"),
    ProgressCategory("sdk", "SDK Code"),
]
config.progress_each_module = args.verbose
# Optional extra arguments to `objdiff-cli report generate`
config.progress_report_args = [
    # Marks relocations as mismatching if the target value is different
    # Default is "functionRelocDiffs=none", which is most lenient
    # "--config functionRelocDiffs=data_value",
]

if args.mode == "configure":
    # Write build.ninja and objdiff.json
    generate_build(config)
elif args.mode == "progress":
    # Print progress information
    calculate_progress(config)
else:
    sys.exit("Unknown mode: " + args.mode)
