#!/usr/bin/env python3
"""
Survey the asset files on the two GW4E69 discs without interpreting them.

    python tools/research/asset_survey.py <disc1_files_dir> <disc2_files_dir> [-o docs/formats/survey.md]

For every file under Data/ and the disc root it records size, the first bytes, and a guess at the
header shape (magic word, big/little-endian counts). Files are grouped by extension and by header
pattern, and the folders present on both discs are compared byte for byte. The output is a
markdown report; nothing is extracted or decoded.
"""
import argparse, hashlib, os, struct, sys
from collections import defaultdict, Counter

EXTS = ('.hog', '.gcb', '.sac', '.fxg', '.ngc', '.sab')

def walk(root):
    out = []
    for dp, dn, fn in os.walk(root):
        for f in fn:
            p = os.path.join(dp, f)
            out.append((os.path.relpath(p, root).replace('\\', '/'), p))
    return sorted(out)

def head(path, n=64):
    with open(path, 'rb') as f:
        return f.read(n)

def printable(b):
    return ''.join(chr(c) if 0x20 <= c < 0x7f else '.' for c in b)

def sha1(path, limit=None):
    h = hashlib.sha1()
    with open(path, 'rb') as f:
        while True:
            c = f.read(1 << 20)
            if not c: break
            h.update(c)
    return h.hexdigest()

def words(b, n=8):
    be = struct.unpack('>%dI' % n, b[:4 * n]) if len(b) >= 4 * n else ()
    le = struct.unpack('<%dI' % n, b[:4 * n]) if len(b) >= 4 * n else ()
    return be, le

def classify(b, size):
    """Very rough header shape: magic text? plausible big-endian counts/offsets?"""
    tags = []
    if len(b) >= 4 and all(0x20 <= c < 0x7f for c in b[:4]):
        tags.append('magic:' + b[:4].decode('latin1'))
    be, le = words(b)
    if be:
        if any(w == size for w in be[:4]): tags.append('BE size in header')
        if any(w == size for w in le[:4]): tags.append('LE size in header')
        if 0 < be[0] < 0x10000: tags.append('BE small first word')
        if 0 < le[0] < 0x10000: tags.append('LE small first word')
        if any(0 < w < size and w % 32 == 0 and w > 32 for w in be[1:6]): tags.append('BE 32-aligned offsets')
    return tags

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('d1'); ap.add_argument('d2'); ap.add_argument('-o', default=None)
    a = ap.parse_args()
    discs = {'d1': walk(a.d1), 'd2': walk(a.d2)}
    lines = []
    P = lines.append
    P('Asset survey'); P('============'); P('')
    P('Generated by `tools/research/asset_survey.py`. Header bytes only; nothing decoded.'); P('')

    # --- per extension summary
    for ext in EXTS:
        P('`%s`' % ext); P('-' * (len(ext) + 2)); P('')
        groups = defaultdict(list)
        sizes = []
        for d, files in discs.items():
            for rel, p in files:
                if not rel.lower().endswith(ext): continue
                size = os.path.getsize(p); sizes.append(size)
                b = head(p)
                key = printable(b[:16])
                groups[key].append((d, rel, size, b))
        if not sizes:
            P('none'); P(''); continue
        P('%d files, %d bytes to %d bytes (total %.1f MiB)' % (len(sizes), min(sizes), max(sizes), sum(sizes) / 2**20)); P('')
        P('| first 16 bytes | files | example | size | tags |'); P('|---|---:|---|---:|---|')
        for key, items in sorted(groups.items(), key=lambda kv: -len(kv[1])):
            d, rel, size, b = items[0]
            P('| `%s` | %d | `%s:%s` | %d | %s |' % (key.replace('|', '/'), len(items), d, rel, size, ', '.join(classify(b, size))))
        P('')
        # one full 64-byte dump of the most common shape
        key, items = max(groups.items(), key=lambda kv: len(kv[1]))
        d, rel, size, b = items[0]
        be, le = words(b, 16)
        P('Header of `%s:%s` (%d bytes):' % (d, rel, size)); P('')
        P('    ' + ' '.join('%02X' % c for c in b[:32])); P('    ' + ' '.join('%02X' % c for c in b[32:64])); P('')
        P('    as big-endian u32: ' + ' '.join('%08X' % w for w in be[:8])); P('    ' + ' '.join('%08X' % w for w in be[8:16])); P('')

    # --- cross-disc comparison
    P('Cross-disc comparison'); P('---------------------'); P('')
    m1 = {rel: p for rel, p in discs['d1']}; m2 = {rel: p for rel, p in discs['d2']}
    both = sorted(set(m1) & set(m2)); only1 = sorted(set(m1) - set(m2)); only2 = sorted(set(m2) - set(m1))
    same = diff = 0; diffs = []
    for rel in both:
        s1, s2 = os.path.getsize(m1[rel]), os.path.getsize(m2[rel])
        if s1 == s2 and sha1(m1[rel]) == sha1(m2[rel]): same += 1
        else: diff += 1; diffs.append((rel, s1, s2))
    P('Files on both discs: %d identical, %d different. Disc 1 only: %d. Disc 2 only: %d.' % (same, diff, len(only1), len(only2))); P('')
    if diffs:
        P('Different:'); P('')
        for rel, s1, s2 in diffs: P('- `%s` (%d vs %d bytes)' % (rel, s1, s2))
        P('')
    # folders
    def folders(names): return Counter(rel.split('/')[1] if rel.startswith('Data/') and rel.count('/') >= 2 else rel.split('/')[0] for rel in names)
    P('Disc 1 only, by folder: ' + ', '.join('%s (%d)' % kv for kv in sorted(folders(only1).items()))); P('')
    P('Disc 2 only, by folder: ' + ', '.join('%s (%d)' % kv for kv in sorted(folders(only2).items()))); P('')

    # --- course folder contents (one example)
    P('A course folder'); P('---------------'); P('')
    course = [rel for rel, p in discs['d1'] if rel.startswith('Data/01_peb/')]
    P('`Data/01_peb/` on disc 1, %d files:' % len(course)); P('')
    for rel in course:
        P('- `%s` %d' % (rel[len('Data/01_peb/'):], os.path.getsize(m1[rel])))
    P('')
    text = '\n'.join(lines) + '\n'
    if a.o:
        with open(a.o, 'w', encoding='utf-8', newline='\n') as f: f.write(text)
        print('wrote', a.o)
    else:
        sys.stdout.write(text)

if __name__ == '__main__':
    main()
